# Tanay 2017-09-19

library(data.table)
library(dplyr)
library(fuzzyjoin)
library(nFactors)
library(RColorBrewer)
library(gplots)

#Read in files. quote="" solves for EOF error that is received
ibm_list = read.csv('../Top 2000 Markets.csv', fileEncoding="latin1")
ibm_list$Company.name <- sapply(ibm_list$Company.name, tolower)
ibm_list$Company.name <- gsub(",","",ibm_list$Company.name)
ibm_list$Company.name <- gsub("co\\.","",ibm_list$Company.name)
ibm_list$Company.name <- gsub("inc\\.","",ibm_list$Company.name)
ibm_list$Company.name <- gsub("ltd\\.","",ibm_list$Company.name)
ibm_list$Company.name <- gsub("sa\\.","",ibm_list$Company.name)
ibm_list$Company.name <- sub(' co$', '', ibm_list$Company.name )
ibm_list$Company.name <- gsub("s.a\\.","",ibm_list$Company.name)
ibm_list$Company.name <- gsub("kg\\.","",ibm_list$Company.name)
ibm_list$Company.name <- gsub('"',"",ibm_list$Company.name)
ibm_list$Company.name <- gsub('\\.',"",ibm_list$Company.name)
ibm_list$Company.name <- gsub(' company',"",ibm_list$Company.name)
ibm_list$Company.name <- gsub(' group',"",ibm_list$Company.name)
ibm_list$Company.name <- gsub(' public limited',"",ibm_list$Company.name)
ibm_list$Company.name <- gsub(' plc',"",ibm_list$Company.name)
ibm_list$Company.name <- trimws(ibm_list$Company.name, which = 'both')
ibm_list <- data.table(ibm_list)

#Read in data from MPW
mpw_data <- read.csv("../Data/GTS_ABM_Variables_Updated.csv",fileEncoding="latin1")
mpw_data$Client_Name <- sapply(mpw_data$Client_Name, tolower)
mpw_data$Client_Name <- gsub(",","", mpw_data$Client_Name)
mpw_data$Client_Name <- gsub(" inc.","",mpw_data$Client_Name)
mpw_data$Client_Name <- gsub('"',"",mpw_data$Client_Name)
mpw_data$Client_Name <- gsub(' sa\\.',"",mpw_data$Client_Name)
mpw_data$Client_Name <- gsub(' s.a\\.',"",mpw_data$Client_Name)
mpw_data$Client_Name <- gsub(' gmbh\\.',"",mpw_data$Client_Name)
mpw_data$Client_Name <- gsub(' ltd\\.',"",mpw_data$Client_Name)
mpw_data$Client_Name <- gsub(' co\\.',"",mpw_data$Client_Name)
mpw_data$Client_Name <- gsub('\\.',"",mpw_data$Client_Name)
mpw_data$Client_Name <- gsub(' company',"",mpw_data$Client_Name)
mpw_data$Client_Name <- gsub(' group',"",mpw_data$Client_Name)
mpw_data$Client_Name <- sub(' co$', '', mpw_data$Client_Name )
mpw_data$Client_Name <- gsub(' public limited',"",mpw_data$Client_Name)
mpw_data$Client_Name <- gsub(' plc',"",mpw_data$Client_Name)
mpw_data$Client_Name <- trimws(mpw_data$Client_Name, which = 'both')
mpw_data <- data.table(mpw_data)

#Create new merged data frame
joined <- ibm_list %>%
  stringdist_inner_join(mpw_data, by = c(Company.name='Client_Name'), max_dist = 2)
unique_comps <- unique(joined[,1:2])
newjoin <- merge(ibm_list,unique_comps,by='X.', all.x = TRUE)